### ISSUE TITLE
Cannot enable open3D on macOS

### ISSUE THREAD

**Issue by enzyme69** [vicdoval/sverchok-open3d#10]
Still getting error when trying to enable Addon:

```
Traceback (most recent call last):
  File "/Applications/BLENDER_31/Blender.app/Contents/Resources/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/sverchok-open3d-master/__init__.py", line 36, in <module>
    from sverchok_open3d import icons, settings, sockets, examples, menu
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.1/scripts/addons/sverchok-open3d-master/settings.py", line 6, in <module>
    PYPATH = sys.executable
NameError: name 'sys' is not defined
```

**Comment by vicdoval** [comment]
That should be fixed, but I'm not if there is a MacOS compatible library of Open3d

**Comment by zeffii** [comment]
oh i forgot to import sys. ?!
