### ISSUE TITLE
impossible enable node in 2.92.0

### ISSUE THREAD

**Issue by JuanJ67m** [vicdoval/sverchok-open3d#3]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-open3d-master\__init__.py", line 64, in <module>
    imported_modules = [icons] + make_node_list()
  File "C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-open3d-master\__init__.py", line 51, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-open3d-master\nodes\point_cloud\point_cloud_in.py", line 10, in <module>
    from sverchok.data_structure import updateNode, has_element
ImportError: cannot import name 'has_element' from 'sverchok.data_structure' (C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-vstable8\data_structure.py)

**Comment by vicdoval** [comment]
Hello @JuanJ67m  
All you need to update your Sverchok

**Comment by vicdoval** [comment]
you can use the buttons in the UI 
![image](https://user-images.githubusercontent.com/10011941/117765680-a87df980-b22e-11eb-9a59-225276d6ec11.png)
or download the lastest master https://github.com/nortikin/sverchok/archive/refs/heads/master.zip
